### ISSUE TITLE
Claims payer list links on readme are dead

### ISSUE THREAD

**Issue by bananatron** [eligible/eligible-ruby#20]
I'm getting 404s on these:
https://eligible.com/resources/claims-payer.xml
https://eligible.com/resources/claims-payer.json

Also, https://eligible.com/rest#demographics

**Comment by ggeligible** [comment]
Hello Spensor,

Thanks for reporting the issue. I have fixed the resources and documentation links on the ReadMe file.

Please feel free to reopen or reach out to us at support@eligible.com if you need any additional information. Have a great day ahead.
