### ISSUE TITLE
Separate debug info and user agent

### ISSUE THREAD

**Issue by abedra** [eligible/eligible-ruby#9]
Right now the user agent is packed with information. This information can be useful but isn't necessary as identifying information. We should limit the user agent for all client libraries to:

`eligible-<language>/<version>`

This gives us just enough information to understand what client they are using. We should allow for the client to send us debug info in a configurable way, and if it is enabled, it should be sent using the

`X-Eligible-DebugInfo`

header. This can include as much information as is necessary for us to analyze failures if they occur.

**Comment by ankitdimania-eligible** [comment]
@abedra I guess the reason it is not helpful right now is because we are supporting only one API version per Library version. If we have to support (quite possible in future) multiple API versions per Library version, then current format becomes logical approach. Please advice here.

**Comment by abedra** [comment]
Version in this case is not the API version, but the version of the client in use.
